FIXUP: CHROMIUM: mali: update kbase to r26p0
The mali update to r26p0 fails to compile all over the place.
Mark affected configuration options as BROKEN.

In file included from include/trace/events/gpu.h:7:0,
                 from drivers/gpu/arm/midgard/mali_kbase.h:76,
                 from drivers/gpu/arm/midgard/mali_kbase_core_linux.c:23:
drivers/gpu/arm/midgard/./mali_linux_kbase_trace.h:33:11: error: expected ) before int
  TP_PROTO(int jobslot, unsigned int info_val),
           ^
drivers/gpu/arm/midgard/./mali_linux_kbase_trace.h:79:11: error: expected ) before int
  TP_PROTO(int refcount, unsigned int info_val),
           ^
drivers/gpu/arm/midgard/./mali_linux_kbase_trace.h:115:11: error: expected ) before int
  TP_PROTO(int gpu_addr, unsigned int info_val),
           ^
In file included from include/trace/define_trace.h:90:0,
                 from drivers/gpu/arm/midgard/mali_linux_kbase_trace.h:205,
                 from drivers/gpu/arm/midgard/mali_kbase_core_linux.c:4209:
include/trace/trace_events.h:25:23: error: redefinition of str__mali__trace_system_name

drivers/gpu/arm/midgard/ipa/mali_kbase_ipa.c:646:3: error: struct devfreq_cooling_power has no member named get_real_power; did you mean get_static_power?
  .get_real_power = &kbase_get_real_power,
   ^~~~~~~~~~~~~~
   get_static_power
drivers/gpu/arm/midgard/ipa/mali_kbase_ipa.c:646:20: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
  .get_real_power = &kbase_get_real_power,
                    ^
drivers/gpu/arm/midgard/ipa/mali_kbase_ipa.c:646:20: note: (near initialization for kbase_ipa_power_model_ops.dyn_power_coeff)
make[4]: [drivers/gpu/arm/midgard/ipa/mali_kbase_ipa.o] Error 1 (ignored)
drivers/gpu/arm/midgard/mali_kbase_core_linux.o: error adding symbols: File in wrong format

BUG=b:111806370
TEST=boot up and login to Kevin

Change-Id: I9395b836523dfe437f66daae7519b3e16ab8c5d1
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1204752
Reviewed-by: Ilja H. Friedel <ihf@chromium.org>