FIXUP: BACKPORT: drm: Remove unused drm_device from drm_gem_object_lookup()
Compile error:

In file included from include/linux/notifier.h:13:0,
                 from include/linux/clk.h:17,
		 from drivers/gpu/drm/armada/armada_crtc.c:9:
drivers/gpu/drm/armada/armada_crtc.c: In function 'armada_drm_crtc_cursor_set':
drivers/gpu/drm/armada/armada_crtc.c:930:14: error: 'dev' undeclared

BUG=b:36446508
TEST=allmodconfig builds without error

Change-Id: I426a3baa739124f51f67c046686274bfbc3776fe
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/506527
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>