CHROMIUM: Mark img-rogue as BROKEN
img-rogue builds are broken since commit 682ab8d3a324 ("FROMLIST: PM / devfreq:
Add struct devfreq_policy").

drivers/gpu/drm/img-rogue/1.9/pvr_dvfs_device.c: In function InitDVFS:
drivers/gpu/drm/img-rogue/1.9/pvr_dvfs_device.c:434:25: error:
	struct devfreq has no member named min_freq
                         ^
drivers/gpu/drm/img-rogue/1.9/pvr_dvfs_device.c:435:25: error:
	struct devfreq has no member named max_freq

Mark it as such.

BUG=b:74321682, b:73050145
TEST=Build arm64:alllmodconfig

Change-Id: Id0fc5ddd6e5b5acfe694086f99077cc6961429e3
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1108188
Reviewed-by: Matthias Kaehlcke <mka@chromium.org>