UPSTREAM: sparc: fix implicit include of slab.h in leon_pci_grpci2.c
To fix:

arch/sparc/kernel/leon_pci_grpci2.c: In function 'grpci2_of_probe':
arch/sparc/kernel/leon_pci_grpci2.c:720:2: error: implicit declaration of function 'kzalloc' [-Werror=implicit-function-declaration]
arch/sparc/kernel/leon_pci_grpci2.c:720:20: error: assignment makes pointer from integer without a cast [-Werror]
arch/sparc/kernel/leon_pci_grpci2.c:882:2: error: implicit declaration of function 'kfree' [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors
make[2]: *** [arch/sparc/kernel/leon_pci_grpci2.o] Error 1

According to Stephen, these types of failures are caused by commit
2bd59d48ebfb ("cgroup: convert to kernfs") which was being included
implicitly via cgroup.h's inclusion of xattr.h (which has now been
removed).

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
Signed-off-by: Tejun Heo <tj@kernel.org>
Acked-by: David S. Miller <davem@davemloft.net>
Cc: Stephen Rothwell <sfr@canb.auug.org.au>

BUG=b:29259708
TEST=Built and booted Minnie

(cherry picked from commit d6250ee2fa79637a5750e46734816c7af71ea97e)
Signed-off-by: Dmitry Torokhov <dtor@chromium.org>
Change-Id: Ibe2c8a2b43d108bc1cc38ab31c20b33c0888ea48
Reviewed-on: https://chromium-review.googlesource.com/359714
Reviewed-by: Dylan Reid <dgreid@chromium.org>