FIXUP: CHROMIUM: iio: cros_ec: Spread timestamps better
Commit 3af8b8cf09074 ("CHROMIUM: iio: cros_ec: Spread timestamps better") causes
test builds to fail.

drivers/iio/common/cros_ec_sensors/cros_ec_sensors_ring.c:
	In function 'cros_ec_ring_fifo_toggle':
drivers/iio/common/cros_ec_sensors/cros_ec_sensors_ring.c:107:2: error:
	'for' loop initial declarations are only allowed in C99 or C11 mode

Furthermore, there are build warnings.

drivers/iio/common/cros_ec_sensors/cros_ec_sensors_ring.c:
	In function cros_ec_ring_handler:
drivers/iio/common/cros_ec_sensors/cros_ec_sensors_ring.c:352:28: warning:
	format %d expects argument of type int, but argument 6 has type s64 {aka long long int}

BUG=b:73551961, b:67743747
TEST="Build with allmodconfig kernel configurations"

Change-Id: Ib9d64c1c21dafecbda405822339e171a6e992cb9
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1085382
Reviewed-by: Alexandru M Stan <amstan@chromium.org>