FIXUP: CHROMIUM: iio: Add SEMTECH SX9320/SX9321 sensor drivers
Building the driver with ACPI disabled results in build errors
such as the following.

drivers/iio/proximity/sx932x.c: In function 'sx932x_read_register_property':
drivers/iio/proximity/sx932x.c:1182:16: error:
		dereferencing pointer to incomplete type 'struct acpi_device'

BUG=b:74586744
TEST=Build with ACPI disabled

Change-Id: Ibdd171ff29409733245c8090eacbde44c7dc5f8e
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1146023
Reviewed-by: Enrico Granata <egranata@chromium.org>
(cherry picked from commit 8a9f4c924d882fa0b05e98234dbcf98c888bb4fe)
Reviewed-on: https://chromium-review.googlesource.com/1147980
Commit-Queue: Jongpil Jung <jongpil19.jung@samsung.corp-partner.google.com>
Tested-by: Jongpil Jung <jongpil19.jung@samsung.corp-partner.google.com>