FROMLIST: mtk-mdp: fix double mutex_unlock
Fix smatch error:
media-git/drivers/media/platform/mtk-mdp/mtk_mdp_vpu.c:100 mtk_mdp_vpu_send_msg()
error: double unlock 'mutex:&ctx->mdp_dev->vpulock'

Signed-off-by: Hans Verkuil <hans.verkuil@cisco.com>
(am from https://patchwork.kernel.org/patch/9338741/)

BUG=chrome-os-partner:57713
TEST=build and boot on elm. Run VDA unittest.

Change-Id: I9131a6c4a4eef2512ab6f6b853caccabcdd7a6b7
Reviewed-on: https://chromium-review.googlesource.com/387448
Commit-Ready: Wu-cheng Li <wuchengli@chromium.org>
Tested-by: Wu-cheng Li <wuchengli@chromium.org>
Reviewed-by: Wu-cheng Li <wuchengli@chromium.org>
(cherry picked from commit 974e8a9b7bc47e90d68de94ff6ed539c36a04b81)
Reviewed-on: https://chromium-review.googlesource.com/388992