CHROMIUM: net: qualcomm: fix CONNTRACK_EVENT compile err
move #ifdef above fast_classifier_update_mark() is compiled together with it's use.

When "CONFIG_NF_CONNTRACK_EVENTS is not set", we get this compile error:

/mnt/host/source/src/third_party/kernel/v3.18/drivers/net/ethernet/qualcomm/sfe/fast-classifier/fast-classifier.c:1122:13: error: 'fast_classifier_update_mark' defined but not used [-Werror=unused-function]
 static void fast_classifier_update_mark(struct sfe_connection_mark *mark, bool is_v4)
             ^
cc1: all warnings being treated as errors

BUG=b:36885509,b:35903996
TEST=emerge-gale gale-kernel-3_18

Change-Id: I8066a14516f08e7249feed4ffca93c6abf9ff8c5
Signed-off-by: Grant Grundler <grundler@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/480700
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>
(cherry picked from commit 4488646ba1b434fe0224485761183737142002a6)
Reviewed-on: https://chromium-review.googlesource.com/491426
Reviewed-by: Hisham Yehia <hyehia@google.com>
Commit-Queue: Srinivasa duvvuri <sduvvuri@chromium.org>
Tested-by: Srinivasa duvvuri <sduvvuri@chromium.org>