FIXUP: CHROMIUM: Add initial version of ar10k wifi drv (take 3)
Test builds (allmodconfig) randomly fail with the following error.

ERROR: "ath10k_htt_rx_pktlog_completion_handler" [drivers/net/wireless/ar10k/ath/ath10k/ath10k_pci.ko] undefined!

This can only happen if both ATH10K and AR10K are built and interfer
with each other. Analysis shows that "depends on !ATH10K" is wrong.
It needs to be "depends on ATH10K=n".

BUG=chromium:686507
TEST=Build x86_64:allmodconfig and observe lack of build errors

Change-Id: I16ea22ff5bfa614660ce4fa57bc743bffae37b7f
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1033486
Reviewed-by: Kirtika Ruchandani <kirtika@chromium.org>