FIXUP: CHROMIUM: mfd: Add new mfd device TPS68470
Enabling MFD_TPS68470 results in the following build errors if I2C
is built as module.

drivers/built-in.o: In function `tps68470_probe':
:(.text+0x287784): undefined reference to `__devm_regmap_init_i2c'
drivers/built-in.o: In function `tps68470_driver_init':
:(.init.text+0x170e0): undefined reference to `i2c_register_driver'
drivers/built-in.o: In function `tps68470_driver_exit':
:(.exit.text+0xf40): undefined reference to `i2c_del_driver'

Its dependency needs to be "I2C=y".

BUG=b:37020027
TEST=compile with I2C=m

Change-Id: Iadaaeb97abe4f637b8e489d6911ef61a9bb81ce7
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/565919
Reviewed-by: Rajmohan Mani <rajmohan.mani@intel.com>
Reviewed-by: Ricky Liang <jcliang@chromium.org>