UPSTREAM: x86/tsc: Make CONFIG_X86_TSC=n build work again
tsc_async_resets is only available when CONFIG_X86_TSC=y. So a build with
CONFIG_X86_TSC=n breaks:

arch/x86/kernel/tsc.o: In function `tsc_init':
(.init.text+0x87b): undefined reference to `tsc_async_resets'

Add a stub define for the TSC=n case.

Side note: This config switch should simply be removed.

Reported-by: kbuild test robot <fengguang.wu@intel.com>
Fixes: 341102c3ef29 ("x86/tsc: Add option that TSC on Socket 0 being non-zero is valid")
Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
Cc: Mike Travis <mike.travis@hpe.com>
(cherry picked from commit c0fc9b1350a317da22b310d68117b0d01cb9065e)

BUG=b:112103715, b:112159884
TEST=Verified that no hang is observed on yorp for 5000+ warm reboots

Change-Id: I856c98d4e9df690b7f0917f392cdb91c157ba9cb
Signed-off-by: Guenter Roeck <groeck@chromium.org>