FIXUP: BACKPORT: drm: Protect fb_defio in drivers with CONFIG_KMS_FBDEV_EMULATION
0day reports:

drivers/gpu/drm/qxl/qxl_fb.c:168:13: error:
	'qxl_deferred_io' defined but not used

Unlike the upstream code, which calls a generic function,
the code in chromeos-4.4 calls a locally defined function.
This function is no longer called if CONFIG_DRM_FBDEV_EMULATION
is not enabled, resulting in the build error.

BUG=b:117899525
TEST=trybot

Change-Id: Id298055abdefa54282ab229407be4f900b45c5b2
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1500113
Reviewed-by: Po-Hsien Wang <pwang@chromium.org>