FIXUP: CHROMIUM: media: intel-ipu3: add dual pipeline support
drivers/media/pci/intel/ipu3/ipu3-css.c: In function ipu3_css_pipeline_init:
drivers/media/pci/intel/ipu3/ipu3-css.c:697:8: error:
	type defaults to int in declaration of stage

Almost no further comment, except that it is difficult to imagine a more
useless variable. And what happened with "upstream first" ?

BUG=b:113305283
TEST=Compile

Change-Id: If039282a012b9077d72ddb0082eb40b6f93a2919
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1205680
Reviewed-by: Zubin Mithra <zsm@chromium.org>
(cherry picked from commit 659114a0ec2388ef70ece8e0b359940be685e325)
Reviewed-on: https://chromium-review.googlesource.com/1213386
Reviewed-by: Ricky Liang <jcliang@chromium.org>
Commit-Queue: Ricky Liang <jcliang@chromium.org>
Tested-by: Ricky Liang <jcliang@chromium.org>