CHROMIUM: ASoC: Intel: boards: fix glk_rt5682_max98357a build errors
with closed FW machine driver, fixed build errors:

sound/soc/intel/boards/glk_rt5682_max98357a.c:583:3: error: use of undeclared identifier 'err'
                err = snd_soc_card_jack_new(card, jack_name,
...
sound/soc/intel/boards/glk_rt5682_max98357a.c:601:34: error: use of undeclared identifier 'err'
                err = snd_soc_card_jack_new(card, jack_name,

BUG=b:118793214
TEST= Verify aplay/arecord -l sound card glkrt5682max exists.

Signed-off-by: Mac Chiang <mac.chiang@intel.com>

Change-Id: I00e090bd4a9f38282805288f0d038e900e3ae299
Reviewed-on: https://chromium-review.googlesource.com/1339379
Commit-Ready: Mac Chiang <mac.chiang@intel.com>
Tested-by: Mac Chiang <mac.chiang@intel.com>
Reviewed-by: Curtis Malainey <cujomalainey@chromium.org>
(cherry picked from commit 07991493c0fbb73c0c38ed80521e65816ef35b47)
Reviewed-on: https://chromium-review.googlesource.com/c/1358279
Reviewed-by: Marco Chen <marcochen@chromium.org>
Commit-Queue: Marco Chen <marcochen@chromium.org>
Tested-by: Marco Chen <marcochen@chromium.org>