CHROMIUM: Fix img-rogue build failure
This fixes up the img-rogue for the changes made in 682ab8d3a324
("FROMLIST: PM / devfreq: Add struct devfreq_policy"). This caused the
img-rogue build to fail with:

    drivers/gpu/drm/img-rogue/1.9/pvr_dvfs_device.c: In function InitDVFS:
    drivers/gpu/drm/img-rogue/1.9/pvr_dvfs_device.c:434:25: error:
        struct devfreq has no member named min_freq
                             ^
    drivers/gpu/drm/img-rogue/1.9/pvr_dvfs_device.c:435:25: error:
        struct devfreq has no member named max_freq

BUG=b:117489304
TEST=cros_workon_make --board=elm --install chromeos-kernel-4_4 #\
 deploy it and boot into ui

Change-Id: I7b998b3a539acdb6a28b012ababd667e0c71e1f4
Signed-off-by: Luigi Santivetti <luigi.santivetti@imagination.corp-partner.google.com>
Reviewed-on: https://chromium-review.googlesource.com/1347172
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>