CHROMIUM: iwl7000: pcie: fix compilation with IWLWIFI_PLATFORM_DATA
I broke compilation when IWLWIFI_PLATFORM_DATA is enabled:

/home/emmanuel/Work/iwlwifi-stack-dev/drivers/net/wireless/intel/iwlwifi/pcie/trans.c:1178:20: error: implicit declaration of function ‘iwl_trans_pcie_power_device_off’ [-Werror=implicit-function-declaration]
  if (low_power && !iwl_trans_pcie_power_device_off(trans_pcie)) {
                    ^

Signed-off-by: Emmanuel Grumbach <emmanuel.grumbach@intel.com>
iwl7000-tree: 3b857f93b34c7a4fe26c2dcdf3bf765b781c52b5