FIXUP: CHROMIUM: PCI: Add double-reset quirk for Marvell 8997
0day reports:

All errors (new ones prefixed by >>):

   drivers//pci/quirks.c: In function 'reset_marvell_wifi_double_flr':
>> drivers//pci/quirks.c:3560:6: error: unused variable 'cap' [-Werror=unused-variable]
     u32 cap;
         ^~~
cc1: all warnings being treated as errors

Indeed, the variable is unused.

BUG=b:64074778
TEST=Build without warning/error

Change-Id: Idd8f1039e8d4d0a706234c0f12015f72edcff432
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1015403
Reviewed-by: Brian Norris <briannorris@chromium.org>