CHROMIUM: x86/mce: Disable 'gcc-compat' warning for mce.c locally
With the warning enabled clang generates a false positive:

arch/x86/kernel/cpu/mcheck/mce.c:1928:12: error: 'break' is bound to loop,
   GCC binds it to switch [-Werror,-Wgcc-compat]
                } while (cmpxchg(&mcelog.flags, flags, 0) != flags);
                         ^
arch/x86/include/asm/cmpxchg.h:147:2: note: expanded from macro 'cmpxchg'
        __cmpxchg(ptr, old, new, sizeof(*(ptr)))
        ^
arch/x86/include/asm/cmpxchg.h:132:2: note: expanded from macro '__cmpxchg'
        __raw_cmpxchg((ptr), (old), (new), (size), LOCK_PREFIX)
        ^
arch/x86/include/asm/cmpxchg.h:123:3: note: expanded from macro '__raw_cmpxchg'
                break;                                                  \
                ^

The problem has been reported to upstream clang:
https://bugs.llvm.org/show_bug.cgi?id=32648

BUG=chromium:709711,chromium:702741
TEST=build for pyro with clang

Change-Id: I2b1087926acaf6dcdec5c15b06e1a8c996ae4f8f
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/508035
Commit-Ready: Douglas Anderson <dianders@chromium.org>
Reviewed-by: Douglas Anderson <dianders@chromium.org>
(cherry picked from commit 3ec3229aaa3a99c8af687d07abe91d96e4f5712c)
Signed-off-by: Matt Atwood <matthew.s.atwood@intel.corp-partner.google.com>