BACKPORT: CHROMIUM: fs: Mark sdcardfs as BROKEN
It doesn't compile.

fs/sdcardfs/sdcardfs.h: In function get_gid:
fs/sdcardfs/sdcardfs.h:418:46: error: struct vfsmount has no member named data

fs/sdcardfs/sdcardfs.h:554:8: error: implicit declaration of function vfs_mkdir2

and so on.

BUG=b:63876697
TEST=None

Change-Id: I04ee30f0c7169e33b66bacf1930f4a5baebcd98f
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/909298
Reviewed-by: Gwendal Grignou <gwendal@google.com>
(cherry picked from commit 83b47c412633e80e133ad9f00b985d206d97b6ab)
Reviewed-on: https://chromium-review.googlesource.com/961714
Tested-by: Gwendal Grignou <gwendal@chromium.org>
Reviewed-by: Gwendal Grignou <gwendal@chromium.org>