UPSTREAM: HID: intel-ish-hid: format 32-bit integers with %X
In ishtp_hid_probe(), use %04X instead of %04hX to format __u32 values,
in order to silent a format error reported by clang:

    drivers/hid/intel-ish-hid/ishtp-hid.c:212:3: error: format specifies
    type 'unsigned short' but the argument has type '__u32' (aka
    'unsigned int') [-Werror,-Wformat]
                    hid->vendor, hid->product);
                    ^~~~~~~~~~~
    drivers/hid/intel-ish-hid/ishtp-hid.c:212:16: error: format
    specifies type 'unsigned short' but the argument has type '__u32'
    (aka 'unsigned int') [-Werror,-Wformat]
                    hid->vendor, hid->product);
                                 ^~~~~~~~~~~~

Signed-off-by: Nicolas Iooss <nicolas.iooss_linux@m4x.org>
Acked-by: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
Signed-off-by: Jiri Kosina <jkosina@suse.cz>
(cherry picked from commit 5299a92a3b98b91b7230662b8b9b6c64bcf8cae6)
Signed-off-by: Rushikesh S Kadam <rushikesh.s.kadam@intel.com>

Bug=b:109857156
Test=Build kernel, boot & verify that Intel ISH driver is loaded
Verify for Trackpad input functionality (requires ISH FW to be
loaded)

Change-Id: Ic966d3070ad1db5e0329757c8d68992215bbff63
(cherry picked from commit 7bf3111dbb1380389564af77775b9a83aa687793)
Reviewed-on: https://chromium-review.googlesource.com/c/1309611
Reviewed-by: Caveh Jalali <caveh@google.com>
Commit-Queue: Caveh Jalali <caveh@google.com>
Tested-by: Caveh Jalali <caveh@google.com>