CHROMIUM: cpuidle: governors: menu:  Fix -Wunused-function
Commit 30977e124478 ("cpuidle: governor: menu: don't use loadavg")
coming from Android (not present upstream) removed the usage of
get_loadavg, but not the function itself, introducing the following
warning, fix it.

menu.c:138:12: error:
'get_loadavg' defined but not used [-Werror=unused-function]
static int get_loadavg(void)

BUG=chromium:702788
TEST=built and ran on samus

Change-Id: I0713afd46c251bcdd4b1f24ac9c16d2d2b61a14a
Signed-off-by: Kirtika Ruchandani <kirtika@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/457237
Reviewed-by: Sonny Rao <sonnyrao@chromium.org>