FROMGIT: cros_ec: fix nul-termination for firmware build info
As gcc-8 reports, we zero out the wrong byte:

drivers/platform/chrome/cros_ec_sysfs.c: In function 'show_ec_version':
drivers/platform/chrome/cros_ec_sysfs.c:190:12: error: array subscript 4294967295 is above array bounds of 'uint8_t[]' [-Werror=array-bounds]

This changes the code back to what it did before changing to a
zero-length array structure.

Fixes: a841178445bb ("mfd: cros_ec: Use a zero-length array for command data")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Benson Leung <bleung@chromium.org>
(cherry picked from commit 50a0d71a5d20e1d3eff1d974fdc8559ad6d74892
from git://git.kernel.org/pub/scm/linux/kernel/git/bleung/chrome-platform.git for-next)
Signed-off-by: Enric Balletbo i Serra <enric.balletbo@collabora.com>