FIXUP: BACKPORT: signal/signalfd: Add support for SIGSYS
In v4.4.y, SIGSYS is only supported if __ARCH_SIGSYS is defined.
Otherwise, we get a build error.

fs/signalfd.c: In function 'signalfd_copyinfo':
fs/signalfd.c:146:33: error: 'siginfo_t' has no member named 'si_call_addr'

BUG=chromium:901557
TEST=kernel compiles for test builds

Change-Id: I315455063033ed4b8d96ba3c11e6e065a77746d6
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1342877
Reviewed-by: Stephen Barber <smbarber@chromium.org>