FIXUP: CHROMIUM: media: ipu3-imgu: Synchronize the code with FROMLIST v6
Commit c30916e8a517 ("CHROMIUM: media: ipu3-imgu: Synchronize the code with
FROMLIST v6") drops a dependency on X86_64. This results in error messages
when building the driver with other architectures, as reported by 0day.

drivers/media//pci/intel/ipu3/ipu3-mmu.c: In function 'ipu3_mmu_alloc_page_table':
drivers/media//pci/intel/ipu3/ipu3-mmu.c:135:2: error:
	implicit declaration of function 'set_memory_uc'; did you mean 'add_memory'?
drivers/media//pci/intel/ipu3/ipu3-mmu.c: In function 'ipu3_mmu_free_page_table':
drivers/media//pci/intel/ipu3/ipu3-mmu.c:146:2: error:
	implicit declaration of function 'set_memory_wb'; did you mean 'add_memory'?

BUG=b:72725948
TEST=Build ia64:allmodconfig

Change-Id: Ic3cd35214644358b83c8ee08f5f3ce52df002b36
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1062006
Reviewed-by: Rajmohan Mani <rajmohan.mani@intel.com>
Reviewed-by: Tomasz Figa <tfiga@chromium.org>