UPSTREAM: ASoC: nau8825: mark pm functions __maybe_unused
The newly added nau8825_dai_is_active() function is only called from
the PM logic that is build-time conditional in this driver, so we get
a warning when CONFIG_PM is disabled:

sound/soc/codecs/nau8825.c:229:13: error: 'nau8825_dai_is_active' defined but not used [-Werror=unused-function]
 static bool nau8825_dai_is_active(struct nau8825 *nau8825)

By replacing the #ifdef around the functions with a __maybe_unused
annotation, the code becomes more robust to this kind of problem
and we no longer get the warning while also slightly improving
readability.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: b50455fab459 ("ASoC: nau8825: cross talk suppression measurement function")
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 4983d32526ab6db2f8bd2288def8abf2da5f37b2)
Signed-off-by: Aditya Swarup <aditya.swarup@intel.com>

BUG=chrome-os-partner:54078
TEST=Playing music, headphone plugged. Close the notebook.
Open the notebook and the sound should not resume with a
pop noise.

Change-Id: I3423732eef6bc85c54c0d3bdf6ea735e0540ce4c
Reviewed-on: https://chromium-review.googlesource.com/415393
Commit-Ready: Cheng-Yi Chiang <cychiang@chromium.org>
Tested-by: Cheng-Yi Chiang <cychiang@chromium.org>
Reviewed-by: John Hsu <kchsu0@nuvoton.corp-partner.google.com>
Reviewed-by: Cheng-Yi Chiang <cychiang@chromium.org>
(cherry picked from commit 6cd149c5d55c415e3d208627b59491a454ccd705)
Reviewed-on: https://chromium-review.googlesource.com/742944
Commit-Queue: Ren Kuo <ren.kuo@quanta.corp-partner.google.com>
Tested-by: Ren Kuo <ren.kuo@quanta.corp-partner.google.com>
Reviewed-by: Ren Kuo <ren.kuo@quanta.corp-partner.google.com>