FROMLIST: selinux: Remove unnecessary check of array base in selinux_set_mapping()
'perms' will never be NULL since it isn't a plain pointer but an array
of u32 values.

This fixes the following warning when building with clang:

security/selinux/ss/services.c:158:16: error: address of array
'p_in->perms' will always evaluate to 'true'
[-Werror,-Wpointer-bool-conversion]
                while (p_in->perms && p_in->perms[k]) {

Link: https://patchwork.kernel.org/patch/9629403/
(applied to github.com SELinuxProject/selinux-kernel next)

BUG=chromium:702741
TEST=build with clang for gru

Change-Id: I653b535546284cdba6e042394de2f45d4028ec71
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Signed-off-by: Paul Moore <paul@paul-moore.com>
Reviewed-on: https://chromium-review.googlesource.com/477465
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>