FROMGIT: selinux: Remove unnecessary check of array base in selinux_set_mapping()
'perms' will never be NULL since it isn't a plain pointer but an array
of u32 values.

This fixes the following warning when building with clang:

security/selinux/ss/services.c:158:16: error: address of array
'p_in->perms' will always evaluate to 'true'
[-Werror,-Wpointer-bool-conversion]
                while (p_in->perms && p_in->perms[k]) {

BUG=chromium:702746
TEST=build for edgar with clang

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Signed-off-by: Paul Moore <paul@paul-moore.com>
(cherry picked from git.kernel.org jmorris/linux-security next
commit 342e91578eb6909529bc7095964cd44b9c057c4e)

Change-Id: I7c7b3998ef4eb63c0a786ff23c208d2afadd9928
Reviewed-on: https://chromium-review.googlesource.com/489611
Commit-Ready: Matthias Kaehlcke <mka@chromium.org>
Tested-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-by: Douglas Anderson <dianders@chromium.org>