UPSTREAM: HID: intel_ish-hid: fix potential uninitialized data usage
gcc points out an uninialized pointer dereference that could happen
if we ever get to recv_ishtp_cl_msg_dma() or recv_ishtp_cl_msg()
with an empty &dev->read_list:

drivers/hid/intel-ish-hid/ishtp/client.c: In function 'recv_ishtp_cl_msg_dma':
drivers/hid/intel-ish-hid/ishtp/client.c:1049:3: error: 'cl' may be used uninitialized in this function [-Werror=maybe-uninitialized]

The warning only appeared in very few randconfig builds, as the
spinlocks tend to prevent gcc from tracing the variables. I only
saw it in configurations that had neither SMP nor LOCKDEP enabled.

As we can see, we only enter the case if 'complete_rb' is non-NULL,
and then 'cl' is known to point to complete_rb->cl. Adding another
initialization to the same pointer is harmless here and makes it
clear to the compiler that the behavior is well-defined.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
Signed-off-by: Jiri Kosina <jkosina@suse.cz>
(cherry picked from commit 1260662fa3f293042fb0ae124c9a621f29f5bcab)
Signed-off-by: Rushikesh S Kadam <rushikesh.s.kadam@intel.com>

Bug=b:109857156
Test=Build kernel, boot & verify that Intel ISH driver is loaded
Verify for Trackpad input functionality (requires ISH FW to be
loaded)

Change-Id: Ie93c9ea6f87ebe4cd0f9a268cc7b7e13c183d03d
(cherry picked from commit b26d9aa8eb009e47a22ecf234e2c595acb604cdc)
Reviewed-on: https://chromium-review.googlesource.com/c/1309614
Reviewed-by: Caveh Jalali <caveh@google.com>
Commit-Queue: Caveh Jalali <caveh@google.com>
Tested-by: Caveh Jalali <caveh@google.com>