UPSTREAM:ASoC: AMD: Add missing include file
arm:allmodconfig, s390:allmodconfig, sparc64:allmodconfig, and probably
other builds fail with

sound/soc/amd/acp-pcm-dma.c:83:2: error:
	implicit declaration of function readl
sound/soc/amd/acp-pcm-dma.c:88:2: error:
	implicit declaration of function writel

Include linux/io.h explicitly to fix the problem.

BUG=b:62103837
TEST=
rmmod snd_soc_rt5645 snd_soc_rl6231 designware_i2s snd_soc_core
cd /lib/modules/4.4.64/kernel/sound/soc/
modprobe snd_soc_core
insmod amd/snd-soc-acp-pcm.ko
insmod dwc/designware_i2s.ko
insmod codecs/snd-soc-rl6231.ko
insmod codecs/snd-soc-rt5645.ko
insmod amd/snd-soc-acp-rt5645.ko
apply mixer setttngs
aplay -D hw:1,0 <file>

Change-Id: Ib0edff9908384ee3cc3156e0aa826428a1f6724d
Fixes: 7c31335a03b6a ("ASoC: AMD: add AMD ASoC ACP 2.x DMA driver")
Cc: Maruthi Srinivas Bayyavarapu <Maruthi.Bayyavarapu@amd.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 7cb1dc810935fbf82ad06007dc7fb08d93c1e59f)
Reviewed-on: https://chromium-review.googlesource.com/554576
Commit-Ready: Akshu Agrawal <akshu.agrawal@amd.com>
Tested-by: Akshu Agrawal <akshu.agrawal@amd.com>
Reviewed-by: Dominik Behr <dbehr@chromium.org>