CHROMIUM: net: xt_qtaguid: Remove unnecessary checks for net_dev.name == NULL
The checks are unnecessary since net_device.name is a character array,
not a pointer.

This fixes two clang warnings like this:

net/netfilter/xt_qtaguid.c:1325:31: error: address of array 'el_dev->name' will
always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]

BUG=chromium:702741
TEST=build with clang for gru

Change-Id: I96c14eecfe72c7202e84f71f758f5373926dc422
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/475973
Reviewed-by: Guenter Roeck <groeck@chromium.org>