CHROMIUM: lkdtm: Change memset usage to use size of destination
When CONFIG_FORTIFY_SOURCE is enabled and the kernel is built with allmodconfig
there is the following compile time error.

In function memset,
    inlined from corrupt_stack at drivers/misc/lkdtm.c:338:2:
include/linux/string.h:278:3: error: call to __write_overflow declared with
attribute error: detected write beyond size of object passed as 1st parameter
   __write_overflow();
   ^~~~~~~~~~~~~~~~~~

Upstream commit 93e78c6b14c("lkdtm: Add -fstack-protector-strong test")
deals with this by moving this memset into another function. Make a
similar change to avoid the compile time error.

BUG=chromium:901062
TEST=Build and boot

Change-Id: I5cc92fb263da556c46ef1ea9ac63b25e853317dc
Signed-off-by: Zubin Mithra <zsm@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1313424
Reviewed-by: Kees Cook <keescook@chromium.org>