FIXUP: CHROMIUM: [media] rockchip-vpu: add rk3399-vdec vp9d
Files using using vmalloc() and vfree() should include linux/vmalloc.h
to avoid the following build errors.

drivers/media/platform/rockchip-vpu/rk3399_vdec_hw_vp9d.c:1218:3: error:
	implicit declaration of function 'vmalloc'

drivers/media/platform/rockchip-vpu/rk3399_vdec_hw_vp9d.c:1231:3: error:
	implicit declaration of function 'vfree'

BUG=chrome-os-partner:55135
TEST=Build

Change-Id: I8c206cbdf954d6b24ecf29ebf20634506f0d7186
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/377380
Reviewed-by: Owen Lin <owenlin@chromium.org>
(cherry picked from commit a0ce3bb24678c095d31f30999b8bd832e66aec7f)
Reviewed-on: https://chromium-review.googlesource.com/379604
Reviewed-by: Mohammed Habibulla <moch@google.com>
Commit-Queue: Mohammed Habibulla <moch@google.com>
Tested-by: Mohammed Habibulla <moch@google.com>