FIXUP: CHROMIUM: iio: Add SEMTECH SX9320/SX9321 sensor drivers
As the driver source itself notes, it depends on ACPI and otherwise
generates build errors such as:

drivers/iio/proximity/sx932x.c: In function 'sx932x_read_register_property':
drivers/iio/proximity/sx932x.c:1182:16: error:
	dereferencing pointer to incomplete type

BUG=b:74586744
TEST=Build with ACPI disabled

Change-Id: Id04523dfe7abcc38c4d6e6b0dc1314f88b92993b
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1159174
Commit-Ready: Enrico Granata <egranata@chromium.org>
Tested-by: Enrico Granata <egranata@chromium.org>
Reviewed-by: Enrico Granata <egranata@chromium.org>