UPSTREAM:ASoC: dwc: make pcm support built-in when necessary
The new PIO mode for the dwc audio driver causes a link failure
when it is built as a loadable module but the audio driver is built-in:

sound/built-in.o: In function `i2s_irq_handler':
:(.text+0x58c64): undefined reference to `dw_pcm_push_tx'
sound/built-in.o: In function `dw_i2s_probe':
:(.text+0x593dc): undefined reference to `dw_pcm_register'

We could link both into a single module, but apparently the
author intended them to be separate, so this instead changes
the Makefile to force the pcm module to be built-in if the
base module is. This is a bit hacky but not as bad as trying
to work around it in Kconfig language.

BUG=b:62103837
TEST=
rmmod snd_soc_rt5645 snd_soc_rl6231 designware_i2s snd_soc_core
cd /lib/modules/4.4.64/kernel/sound/soc/
modprobe snd_soc_core
insmod amd/snd-soc-acp-pcm.ko
insmod dwc/designware_i2s.ko
insmod codecs/snd-soc-rl6231.ko
insmod codecs/snd-soc-rt5645.ko
insmod amd/snd-soc-acp-rt5645.ko
apply mixer setttngs
aplay -D hw:1,0 <file>

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 79361b2b98b7 ("ASoC: dwc: Add PIO PCM extension")
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 3276d0aa0bf475cc6cfb505487b2a2f3f762aebb)

Change-Id: Ie5a9bb626a46114ebbba3fb2cb60577eef76b468
Reviewed-on: https://chromium-review.googlesource.com/603567
Commit-Ready: Akshu Agrawal <akshu.agrawal@amd.com>
Tested-by: Akshu Agrawal <akshu.agrawal@amd.com>
Reviewed-by: Benson Leung <bleung@chromium.org>