FROMLIST: ALSA: hda/ca0132: Remove double parentheses
The extra pairs of parantheses are not needed and causes clang to
generate warnings like this:

sound/pci/hda/patch_ca0132.c:1171:14: error: equality comparison with extraneous parentheses [-Werror,-Wparentheses-equality]
        if ((buffer == NULL))
             ~~~~~~~^~~~~~~
sound/pci/hda/patch_ca0132.c:1171:14: note: remove extraneous parentheses around the comparison to silence this warning
        if ((buffer == NULL))
            ~       ^      ~
sound/pci/hda/patch_ca0132.c:1171:14: note: use '=' to turn this equality comparison into an assignment
        if ((buffer == NULL))

Link: https://patchwork.kernel.org/patch/9626833/
(accepted by maintainer)

BUG=chromium:702746
TEST=build for edgar with clang

Change-Id: I09a2debde6b4a038d1edea09643a4122c320ba80
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/489431
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>