CHROMIUM: task_work: Disable 'gcc-compat' warning locally
With the warning enabled clang generates a false positive when
building for x86:

kernel/task_work.c:101:12: error: 'break' is bound to current loop,
    GCC binds it to the enclosing loop [-Werror,-Wgcc-compat]
                } while (cmpxchg(&task->task_works, work, head) != work);
                         ^
arch/x86/include/asm/cmpxchg.h:147:2: note: expanded from macro 'cmpxchg'
        __cmpxchg(ptr, old, new, sizeof(*(ptr)))
        ^
arch/x86/include/asm/cmpxchg.h:132:2: note: expanded from macro '__cmpxchg'
        __raw_cmpxchg((ptr), (old), (new), (size), LOCK_PREFIX)
        ^
arch/x86/include/asm/cmpxchg.h:123:3: note: expanded from macro '__raw_cmpxchg'
                break;                                                  \
                ^

The problem has been reported to upstream clang:
https://bugs.llvm.org/show_bug.cgi?id=32648

BUG=chromium:709711,chromium:702741
TEST=build for pyro with clang

Change-Id: I9e07e6aef0e95837fb40d575f60b292baaf6a4eb
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/508036
Commit-Ready: Douglas Anderson <dianders@chromium.org>
Reviewed-by: Douglas Anderson <dianders@chromium.org>
(cherry picked from commit 32d99d5ec678fd2c0a055bf4a6c9c4d62a0776cd)
Signed-off-by: Matt Atwood <matthew.s.atwood@intel.corp-partner.google.com>