FIXUP: CHROMIUM: [media] intel-ipu3: imgu top level pci device
The driver calls clflush_cache_range(), which is only available on x86 and
ia64. If compiled for other architectures, this results in the following
build errors, as reported by Intel's 0day build system.

All errors (new ones prefixed by >>):

  drivers/media//pci/intel/ipu3/ipu3-mmu.c: In function 'ipu3_mmu_alloc_page_table':
>> drivers/media//pci/intel/ipu3/ipu3-mmu.c:155:2: error: implicit
>> declaration of function 'clflush_cache_range'
>> [-Werror=implicit-function-declaration]
  clflush_cache_range(pt, IPU3_PT_PTES * sizeof(*pt));
  ^~~~~~~~~~~~~~~~~~~
--
  drivers/media//pci/intel/ipu3/ipu3-dmamap.c: In function 'flush_page':
>> drivers/media//pci/intel/ipu3/ipu3-dmamap.c:46:2: error:
>> implicit declaration of function 'clflush_cache_range'
>> [-Werror=implicit-function-declaration]
  clflush_cache_range((void *)virt, PAGE_SIZE);
  ^~~~~~~~~~~~~~~~~~~

BUG=b:37020027
TEST=Try to build on non-Intel architecture

Change-Id: Ic210eb56d97ccab9ec5d1e287288e6ec9f6064df
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/565918
Reviewed-by: Tomasz Figa <tfiga@chromium.org>