BACKPORT: FIXUP: CHROMIUM: esdfs: Add option to set base namespace
Building ESD_FS as module fails with:

ERROR: "proc_ns_fget" [fs/esdfs/esdfs.ko] undefined!
ERROR: "userns_operations" [fs/esdfs/esdfs.ko] undefined!

Export both to fix the problem. Also make the new dependency
on USER_NS explicit.

Modify fs/proc/namespaces.c instead of fs/nsfs.c.

BUG=b:63876697
TEST=Build esdfs as module

Change-Id: I82e6a891cf3de8d80683dd57b815f5917cb6a826
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1055685
Reviewed-by: Gwendal Grignou <gwendal@chromium.org>
(cherry picked from commit 1c15351edef79308a4d6e1406752610691151dc1)
Signed-off-by: Gwendal Grignou <gwendal@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1066275