FIXUP: FROMLIST: misc: throttler: Add core support for non-thermal throttling
If PM_DEVFREQ is not enabled, builds fail as as follows.

drivers/misc/throttler/core.c: In function thr_update_devfreq:
drivers/misc/throttler/core.c:458:3: error:
	implicit declaration of function update_devfreq

drivers/misc/throttler/core.c: In function throttler_setup:
drivers/misc/throttler/core.c:616:14: error:
	devfreq_class undeclared

Add the missing dependency on PM_DEVFREQ.

Reported by 0day.

BUG=b:74321682, b:73050145
TEST=Build with PM_DEVFREQ disabled

Change-Id: I2e49098e56e61383d3ad63b9db1e92ca92666eb5
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1155726
Reviewed-by: Matthias Kaehlcke <mka@chromium.org>