CHROMIUM: Use simple_strtoull like upstream xtables
Commit ef3e02ceed67 ("CHROMIUM: config: Add xt_quota2 for Android")
introduced xt_quota2 into 3.14 and also fixed a couple of checkpatch
warnings by changing simple_strtoull usage to kstrtoll.This makes it
inconsistent with xt_quota2 in 3,18 and 4.4 kernels, and introduces
-Wunused-result that breaks the build with -Werror. Revert to
upstream usage.

xt_quota2.c:173:3: error: ignoring return value of 'kstrtoll', declared
with attribute warn_unused_result [-Werror=unused-result]
   kstrtoll(buf + 1, 0, &temp);
   ^

Fixes: ef3e02ceed67 ("CHROMIUM: config: Add xt_quota2 for Android")

BUG=chromium:702788
TEST=built and ran on samus

Change-Id: I9511f550c03ed27124abe26247db4607127b1776
Signed-off-by: Kirtika Ruchandani <kirtika@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/457238
Reviewed-by: Kevin Cernekee <cernekee@chromium.org>