UPSTREAM: drm.h: use __kernel_size_t instead of size_t
Fall back to size_t for non Linux platforms.

Fixes userspace compilation error:

drm/drm.h:132:2: error: unknown type name ‘size_t’

Signed-off-by: Mikko Rapeli <mikko.rapeli@iki.fi>
(cherry picked from commit 1a2a42c8bfa25ef0f7e14c5973c6a0bebe625a96)
from v4.5-rc1
Signed-off-by: Tarun <tarun.vyas@intel.com>

BUG=b:36446508
TEST=No regressions in KBL and APL based devices

Change-Id: Ie6fd544777c033c978ea64046223a0269f927391