Revert "BACKPORT: bpf: don't let ldimm64 leak map addresses on unprivileged"
This reverts commit 963af7824c4e232d4fa62bab2f7d3bbde895de53.

Reason for revert:

Turns out this patch isn't needed in 3.18 since the patch it fixes was only introduced post-3.18. In fact, if the added code is build enabled, it causes a build error discovered by 0day.

kernel/bpf/verifier.c: In function 'print_bpf_insn':
kernel/bpf/verifier.c:391:23: error: 'const struct verifier_env' has no member named 'allow_ptr_leaks'

Original change's description:
> BACKPORT: bpf: don't let ldimm64 leak map addresses on unprivileged
>
> The patch fixes two things at once:
>
> 1) It checks the env->allow_ptr_leaks and only prints the map address to
>    the log if we have the privileges to do so, otherwise it just dumps 0
>    as we would when kptr_restrict is enabled on %pK. Given the latter is
>    off by default and not every distro sets it, I don't want to rely on
>    this, hence the 0 by default for unprivileged.
>
> 2) Printing of ldimm64 in the verifier log is currently broken in that
>    we don't print the full immediate, but only the 32 bit part of the
>    first insn part for ldimm64. Thus, fix this up as well; it's okay to
>    access, since we verified all ldimm64 earlier already (including just
>    constants) through replace_map_fd_with_map_ptr().
>
> BUG=chromium:727008
> TEST=Build and run
>
> Change-Id: I60bc456ba385fd875374e35ebe4689e03d84357b
> Fixes: 1be7f75d1668 ("bpf: enable non-root eBPF programs")
> Fixes: cbd357008604 ("bpf: verifier (add ability to receive verification log)")
> Reported-by: Jann Horn <jannh@google.com>
> Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
> Acked-by: Alexei Starovoitov <ast@kernel.org>
> Signed-off-by: David S. Miller <davem@davemloft.net>
> [backport: struct bpf_verifier_env used to be struct verifier_env]
> Signed-off-by: Guenter Roeck <groeck@chromium.org>
> (cherry picked from commit 0d0e57697f1)
> Reviewed-on: https://chromium-review.googlesource.com/517992

BUG=chromium:727008

Change-Id: I7b92ed28b8f03546a1e51c6c0ff2e285be9e5e0b
Reviewed-on: https://chromium-review.googlesource.com/527258
Commit-Ready: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>