FIXUP: CHROMIUM: LSM: make modules FS pinning work with unshared mount namespace
Above commit introduces a dependency on BLOCK. If CONFIG_BLOCK is undefined,
builds fail with the following error.

security/chromiumos/lsm.c: In function check_locking_enforcement:
security/chromiumos/lsm.c:184:8: error:
	implicit declaration of function bdev_read_only

Reported by 0day.

BUG=b:27720867
TEST=Build with CONFIG_BLOCK disabled

Change-Id: I7fe67890a067e04a9de669698421a43fed69c5c6
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1155725
Reviewed-by: Matthias Kaehlcke <mka@chromium.org>