CHROMIUM: partitions/efi: Fix print specifier warning
Commit abba28d0a1b7 ("CHROMIUM: block: partitions: efi: Add support for
IGNOREME GPT signature") introduced the following warning, omiting an
argument for pr_debug format string, fix it.

partitions/efi.c: In function 'is_gpt_valid':
partitions/efi.c:372:3: error: format '%llu' expects a matching
'long long unsigned int' argument [-Werror=format=]
   pr_debug("GUID Partition Table at LBA %llu marked IGNOREME\n");

BUG=chromium:702788
TEST=built and ran on samus

Change-Id: I712c18b62055428d6d24c46216a75c0fa48916ef
Signed-off-by: Kirtika Ruchandani <kirtika@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/457236
Commit-Ready: Gwendal Grignou <gwendal@chromium.org>
Tested-by: Gwendal Grignou <gwendal@chromium.org>
Reviewed-by: Gwendal Grignou <gwendal@chromium.org>
Reviewed-by: Kevin Cernekee <cernekee@chromium.org>