CHROMIUM: iwl7000: mvm: fix compilation with IWLMVM_AX_SOFTAP_TESTMODE
If IWLMVM_AX_SOFTAP_TESTMODE is set but IWLWIFI_DEVICE_TESTMODE is
not, compilation breaks:

/home/luca/iwlwifi/stack-dev/drivers/net/wireless/intel/iwlwifi/mvm/mac80211.c:5055:21: error: 'iwl_mvm_ax_softap_testmode_sta_add_debugfs' undeclared here (not in a function)
  .sta_add_debugfs = iwl_mvm_ax_softap_testmode_sta_add_debugfs,
                     ^
scripts/Makefile.build:258: recipe for target '/home/luca/iwlwifi/stack-dev/drivers/net/wireless/intel/iwlwifi/mvm/mac80211.o' failed

This is because we erroneously check for IWLWIFI_DEVICE_TESTMODE
before defining the function in mvm.h.

Signed-off-by: Luca Coelho <luciano.coelho@intel.com>
iwl7000-tree: 607085111b87af2ba7ad2c3567b8d291534c78cc