BACKPORT: mfd: Add support for TPS68470 device
The TPS68470 device is an advanced power management
unit that powers a Compact Camera Module (CCM),
generates clocks for image sensors, drives a dual
LED for Flash and incorporates two LED drivers for
general purpose indicators.

This patch adds support for TPS68470 mfd device.

Signed-off-by: Rajmohan Mani <rajmohan.mani@intel.com>
Signed-off-by: Lee Jones <lee.jones@linaro.org>
(cherry picked from commit 9bbf6a15ce19dd947b7fa6ad4095931ab3682da8)

Included <linux/module.h> to fix the following compilation error.

drivers/mfd/tps68470.c:97:1: error: data definition has no type or
storage class [-Werror]
 MODULE_DEVICE_TABLE(acpi, tps68470_acpi_ids);
 ^

Did "git add drivers/mfd/Kconfig" to fix the following conflict.

Conflicts:
	drivers/mfd/Kconfig

BUG=b:37020027
TEST=Ensure image capture works fine in Soraka with both sensors

Change-Id: I8b487c53e7f74ce74a2e528095043d59df01e60b
Signed-off-by: Rajmohan Mani <rajmohan.mani@intel.com>
Reviewed-on: https://chromium-review.googlesource.com/745030
Reviewed-by: Tomasz Figa <tfiga@chromium.org>