UPSTREAM: usb: dwc2: USB_DWC2 should depend on HAS_DMA
If NO_DMA=y:

    ERROR: "usb_gadget_map_request" [drivers/usb/dwc2/dwc2.ko] undefined!
    ERROR: "usb_gadget_unmap_request" [drivers/usb/dwc2/dwc2.ko] undefined!
    ERROR: "bad_dma_ops" [drivers/usb/dwc2/dwc2.ko] undefined!

Add a dependency on HAS_DMA to fix this.

BUG=chrome-os-partner:50683
TEST=USB still works OK

Change-Id: I03dfb7b8514f3bbaa30ec330a40b8bee8739886e
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Acked-by: John Youn <johnyoun@synopsys.com>
Signed-off-by: Felipe Balbi <balbi@kernel.org>
Signed-off-by: Douglas Anderson <dianders@chromium.org>
(cherry picked from commit ee89b641a9ddca5f2d1e38d205473c4b0d26c670)
Reviewed-on: https://chromium-review.googlesource.com/330148
Reviewed-by: Julius Werner <jwerner@chromium.org>