FIXUP: UPSTREAM: drm/udl: make fbdev support really optional
Commit 12a78f269a7a ("UPSTREAM: drm/udl: make fbdev support really
optional") removes "select FB_DEFERRED_IO" from "config DRM_UDL".
If DRM_UDL and DRM_FBDEV_EMULATION are enabled, but FB_DEFERRED_IO
is not enabled by other means, the build now fails with:

drivers/gpu//drm/udl/udl_fb.c: In function 'udlfb_dpy_deferred_io':
drivers/gpu//drm/udl/udl_fb.c:92:39: error:
	'struct fb_info' has no member named 'fbdefio'

as reported by 0day.

Select FB_DEFERRED_IO from DRM_FBDEV_EMULATION to fix the problem.

Note that upstream does not have the problem, since FB_DEFERRED_IO
was added to DRM_KMS_FB_HELPER with commit eaa434defaca1 ("drm/fb-helper:
Add fb_deferred_io support"). It might be possible to pull in that commit
instead, but I decided not to do it to avoid possible side effects.

BUG=b:117899525
TEST=Build with CONFIG_DRM_FBDEV_EMULATION=y

Change-Id: Ie440170ea103a491adb35b926ee892fff8994aec
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1493160
Reviewed-by: Po-Hsien Wang <pwang@chromium.org>
Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>