Reland "FIXUP: CHROMIUM: iwl7000: mvm: enable configuring SAR profile during interface down"
This is a reland of 2cdc7f72cabe8342c3aca52616e3c6ce214b7825 which was
unintentionally reverted while merging bugfixes to Core28 here:
https://chromium-review.googlesource.com/#/c/chromiumos/third_party/kernel/+/606679/

> Builds with CONFIG_ACPI disabled fail as follows.
>
> drivers/net/wireless/iwl7000/iwlwifi/mvm/fw.c: In function 'iwl_mvm_sar_init':
> drivers/net/wireless/iwl7000/iwlwifi/mvm/fw.c:1598:9: error:
> 	'struct iwl_mvm' has no member named 'sar_chain_a_profile'
> drivers/net/wireless/iwl7000/iwlwifi/mvm/fw.c:1598:37: error:
> 	'struct iwl_mvm' has no member named 'sar_chain_b_profile'
>
> because the structure members are only available with CONFIG_ACPI.
>
> BUG=b:63087196
> TEST=Build with IWL7000 enabled and ACPI disabled
>
> Change-Id: I8d801390a5ac6a36a4a179957225cc109a8f5521
> Signed-off-by: Guenter Roeck <groeck@chromium.org>
> Reviewed-on: https://chromium-review.googlesource.com/582076
> Reviewed-by: Kirtika Ruchandani <kirtika@chromium.org>

Change-Id: I43302aa854a4376946946d2d4853e23abeb70bcb