CHROMIUM: WAR: rpmsg: glink: Remove unused variable
drivers/rpmsg/qcom_glink_native.c:1654:16: error: unused variable 'flags'
[-Werror,-Wunused-variable]

unsigned long flags;

1 error generated.

BUG=b:138962769
TEST=COMPILE

Change-Id: Id46de154e801da715fb6fd3a76b0f0abee2075b2
Signed-off-by: Khasim Syed Mohammed <khasim.mohammed@linaro.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1848146
Reviewed-by: Zhihong Yu <zhihongyu@chromium.org>
Commit-Queue: Zhihong Yu <zhihongyu@chromium.org>
Tested-by: Zhihong Yu <zhihongyu@chromium.org>
(cherry picked from commit ba971c917ef71d094e8e42ca3a0559e038e08b61)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1863747