FIXUP: FIXUP: FROMLIST: media: ov2685: add support for OV2685 sensor
In file included from drivers/media/i2c/ov2685.c:13:0:
drivers/media/i2c/ov2685.c:828:25: error:
	'ov5695_of_match' undeclared here (not in a function)
MODULE_DEVICE_TABLE(of, ov5695_of_match);

BUG=b:36227021, b:71686148
TEST=Build with CONFIG_OF enabled

Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/868494
Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
Tested-by: Shunqian Zheng <zhengsq@rock-chips.com>
Reviewed-by: Tomasz Figa <tfiga@chromium.org>

(cherry picked from commit b61954562dcd8d993756f3be792f5a9b1781be78)

Change-Id: I020defdeb6a421f7636f42bd8630d933afd29aa6
Reviewed-on: https://chromium-review.googlesource.com/875675
Reviewed-by: Ricky Liang <jcliang@chromium.org>
Tested-by: Ricky Liang <jcliang@chromium.org>
Commit-Queue: Ricky Liang <jcliang@chromium.org>