FIXUP: CHROMIUM: media: rockchip-vpu: Implement encoder commands
0day reports:

All errors (new ones prefixed by >>):

   drivers/media/platform/rockchip-vpu/rockchip_vpu_enc.c:
   		In function 'rockchip_vpu_encoder_cmd':
>> drivers/media/platform/rockchip-vpu/rockchip_vpu_enc.c:1042:27: error:
		unused variable 'buf' [-Werror=unused-variable]
     struct rockchip_vpu_buf *buf = NULL;
                              ^~~
   cc1: all warnings being treated as errors

BUG=b:71882314
TEST=CtsVideoTestCases on Kevin

Change-Id: Ia11f0b05a95082e8740027af874c817024f40f50
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/955960
Commit-Ready: Pawel Osciak <posciak@chromium.org>
Reviewed-by: Pawel Osciak <posciak@chromium.org>
(cherry picked from commit f767e9b9f710f5816361c2f498f615dd215ee24d)
Reviewed-on: https://chromium-review.googlesource.com/959411
Reviewed-by: Chih-Yu Huang <akahuang@chromium.org>
Commit-Queue: Chih-Yu Huang <akahuang@chromium.org>
Tested-by: Chih-Yu Huang <akahuang@chromium.org>