FROMGIT: pinctrl/amd: Fix build dependency on pinmux code
The commit 79d2c8bede2c93f943 ("pinctrl/amd: save pin registers over
suspend/resume") caused the following compilation errors:

drivers/pinctrl/pinctrl-amd.c: In function amd_gpio_should_save:
drivers/pinctrl/pinctrl-amd.c:741:8: error: const struct pin_desc has no member named mux_owner
  if (pd->mux_owner || pd->gpio_owner ||
        ^
drivers/pinctrl/pinctrl-amd.c:741:25: error: const struct pin_desc has no member named gpio_owner
  if (pd->mux_owner || pd->gpio_owner ||

We need to enable CONFIG_PINMUX for this driver as well.

Cc: stable@vger.kernel.org
Fixes: 79d2c8bede2c93f943 ("pinctrl/amd: save pin registers over suspend/resume")
Signed-off-by: Petr Mladek <pmladek@suse.com>
Signed-off-by: Linus Walleij <linus.walleij@linaro.org>
(cherry picked from commit 83b31c2a5fdd4fb3a4ec84c59a962e816d0bc9de
 git://git.kernel.org/pub/scm/linux/kernel/git/linusw/linux-pinctrl.git
 fixes)
Signed-off-by: Daniel Kurtz <djkurtz@chromium.org>

BUG=b:65597554
TEST=Cherry-pick CL:674892
  emerge-kahlee chromeos-kernel-4_12
  => Builds w/out error:
	drivers/pinctrl/pinctrl-amd.c: In function 'amd_gpio_should_save':
	drivers/pinctrl/pinctrl-amd.c:749:8: error: 'const struct pin_desc' has no member named 'mux_owner'
	  if (pd->mux_owner || pd->gpio_owner ||
		^
	drivers/pinctrl/pinctrl-amd.c:749:25: error: 'const struct pin_desc' has no member named 'gpio_owner'
	  if (pd->mux_owner || pd->gpio_owner ||
		                 ^

Change-Id: I634cf3bbcd6ee81ad1636fb265bf4fe17f7132d6
Reviewed-on: https://chromium-review.googlesource.com/707635
Commit-Ready: Daniel Kurtz <djkurtz@chromium.org>
Tested-by: Daniel Kurtz <djkurtz@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>