CHROMIUM: security: export security_path_chown
esdfs calls security_path_chown, which is not exported. Attempts to build
it as module fail with

ERROR: "security_path_chown" [fs/esdfs/esdfs.ko] undefined!

Making it boolean would also require making PKGLIST, which it depends on,
boolean. Let's export security_path_chown instead.

BUG=b:63876697
TEST=compilation, mount esdfs

Change-Id: If1d833578c1f2c1f25462d72c6de725147a41563
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/919542
Reviewed-by: Sarthak Kukreti <sarthakkukreti@chromium.org>