FIXUP: CHROMIUM: alt-syscall: fallocate emulation.
Fix the following build errors, seen with various allmodconfig builds,
by exporting the respective functions.

ERROR: "sys_ftruncate" [security/chromiumos/alt-syscall.ko] undefined!
ERROR: "sys_fallocate" [security/chromiumos/alt-syscall.ko] undefined!

BUG=b:29732697
TEST=Build arm64:allmodconfig

Change-Id: Ic411ca33c4db1437419c3fbbfb41678b5021150f
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/361330
Commit-Ready: Guenter Roeck <groeck@google.com>
Tested-by: Guenter Roeck <groeck@google.com>
Reviewed-by: Dylan Reid <dgreid@chromium.org>
(cherry picked from commit fe8ff8b9fb5717d6974a8ec44631145fef24a1c9)
Reviewed-on: https://chromium-review.googlesource.com/362533
Trybot-Ready: Hidehiko Abe <hidehiko@chromium.org>
Tested-by: Hidehiko Abe <hidehiko@chromium.org>
Reviewed-by: Guenter Roeck <groeck@google.com>
Commit-Queue: Hidehiko Abe <hidehiko@chromium.org>