UPSTREAM: usb: add HAS_IOMEM dependency to USB_DWC2
drivers/built-in.o: In function `dwc2_driver_probe':
/home/vegard/linux/drivers/usb/dwc2/platform.c:491: undefined reference to `devm_ioremap_resource'

BUG=chrome-os-partner:50683
TEST=USB still works OK

Change-Id: I9f5b887bd7cd9c6adb2308a4d09d801eeb197a50
Signed-off-by: Vegard Nossum <vegard.nossum@oracle.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Douglas Anderson <dianders@chromium.org>
(cherry picked from git.kernel.org balbi/usb.git next
 commit 89f1ec8ee251920dd1bf07abf7a14c62d81d5733)
Reviewed-on: https://chromium-review.googlesource.com/330149
Reviewed-by: Julius Werner <jwerner@chromium.org>