FIXUP: CHROMIUM: mfd: cros_ec_pd_update: Add driver for updating of PD device firmware
CROS_EC_CHARDEV depends on MFD_CROS_EC_PD_UPDATE. Otherwise, we
may get the following build error (seen, for example, when building
arm:exynos_defconfig).

Error log:
drivers/built-in.o: In function `.LANCHOR2':
:(.data+0x1c6e8): undefined reference to `cros_ec_pd_attr_group'

BUG=None
TEST="Build arm:exynos_defconfig"

Change-Id: Iee5a403d1c9952b238cadcebf42ae11e058821b1
Reported-by: Olof Johansson <olof@lixom.net>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/687865
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>